// @define version

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        (unknown)
// source: pal/address/addresslist.proto

// @add package

package peers_peers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Peers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uid     int32  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Eve     bool   `protobuf:"varint,3,opt,name=eve,proto3" json:"eve,omitempty"`
	Pwallet string `protobuf:"bytes,4,opt,name=pwallet,proto3" json:"pwallet,omitempty"`
}

func (x *Peers) Reset() {
	*x = Peers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pal_address_addresslist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Peers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peers) ProtoMessage() {}

func (x *Peers) ProtoReflect() protoreflect.Message {
	mi := &file_pal_address_addresslist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peers.ProtoReflect.Descriptor instead.
func (*Peers) Descriptor() ([]byte, []int) {
	return file_pal_address_addresslist_proto_rawDescGZIP(), []int{0}
}

func (x *Peers) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Peers) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Peers) GetEve() bool {
	if x != nil {
		return x.Eve
	}
	return false
}

func (x *Peers) GetPwallet() string {
	if x != nil {
		return x.Pwallet
	}
	return ""
}

type Contacts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Friend []*Peers `protobuf:"bytes,1,rep,name=friend,proto3" json:"friend,omitempty"`
}

func (x *Contacts) Reset() {
	*x = Contacts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pal_address_addresslist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Contacts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contacts) ProtoMessage() {}

func (x *Contacts) ProtoReflect() protoreflect.Message {
	mi := &file_pal_address_addresslist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contacts.ProtoReflect.Descriptor instead.
func (*Contacts) Descriptor() ([]byte, []int) {
	return file_pal_address_addresslist_proto_rawDescGZIP(), []int{1}
}

func (x *Contacts) GetFriend() []*Peers {
	if x != nil {
		return x.Friend
	}
	return nil
}

var File_pal_address_addresslist_proto protoreflect.FileDescriptor

var file_pal_address_addresslist_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x61, 0x6c, 0x2f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2f, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x59, 0x0a, 0x05, 0x50, 0x65, 0x65, 0x72,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x76, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x65, 0x76, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x77, 0x61,
	0x6c, 0x6c, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x77, 0x61, 0x6c,
	0x6c, 0x65, 0x74, 0x22, 0x32, 0x0a, 0x08, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x73, 0x12,
	0x26, 0x0a, 0x06, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x73, 0x52,
	0x06, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x32, 0x9c, 0x01, 0x0a, 0x06, 0x4d, 0x79, 0x42, 0x6f,
	0x6f, 0x6b, 0x12, 0x2d, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x50, 0x65, 0x65, 0x72, 0x73, 0x12, 0x0e,
	0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x73, 0x1a, 0x11,
	0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74,
	0x73, 0x12, 0x31, 0x0a, 0x0c, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x50, 0x65, 0x65, 0x72,
	0x73, 0x12, 0x0e, 0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x50, 0x65, 0x65, 0x72,
	0x73, 0x1a, 0x11, 0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x63, 0x74, 0x73, 0x12, 0x30, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x65,
	0x65, 0x72, 0x73, 0x12, 0x0e, 0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x50, 0x65,
	0x65, 0x72, 0x73, 0x1a, 0x11, 0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x63, 0x74, 0x73, 0x42, 0x28, 0x5a, 0x26, 0x68, 0x74, 0x74, 0x70, 0x73, 0x3a,
	0x2f, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x69,
	0x32, 0x32, 0x31, 0x30, 0x2f, 0x70, 0x65, 0x65, 0x72, 0x73, 0x2d, 0x70, 0x65, 0x65, 0x72, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pal_address_addresslist_proto_rawDescOnce sync.Once
	file_pal_address_addresslist_proto_rawDescData = file_pal_address_addresslist_proto_rawDesc
)

func file_pal_address_addresslist_proto_rawDescGZIP() []byte {
	file_pal_address_addresslist_proto_rawDescOnce.Do(func() {
		file_pal_address_addresslist_proto_rawDescData = protoimpl.X.CompressGZIP(file_pal_address_addresslist_proto_rawDescData)
	})
	return file_pal_address_addresslist_proto_rawDescData
}

var file_pal_address_addresslist_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pal_address_addresslist_proto_goTypes = []interface{}{
	(*Peers)(nil),    // 0: address.Peers
	(*Contacts)(nil), // 1: address.Contacts
}
var file_pal_address_addresslist_proto_depIdxs = []int32{
	0, // 0: address.Contacts.friend:type_name -> address.Peers
	0, // 1: address.MyBook.AddPeers:input_type -> address.Peers
	0, // 2: address.MyBook.DisplayPeers:input_type -> address.Peers
	0, // 3: address.MyBook.DeletePeers:input_type -> address.Peers
	1, // 4: address.MyBook.AddPeers:output_type -> address.Contacts
	1, // 5: address.MyBook.DisplayPeers:output_type -> address.Contacts
	1, // 6: address.MyBook.DeletePeers:output_type -> address.Contacts
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pal_address_addresslist_proto_init() }
func file_pal_address_addresslist_proto_init() {
	if File_pal_address_addresslist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pal_address_addresslist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Peers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pal_address_addresslist_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Contacts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pal_address_addresslist_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pal_address_addresslist_proto_goTypes,
		DependencyIndexes: file_pal_address_addresslist_proto_depIdxs,
		MessageInfos:      file_pal_address_addresslist_proto_msgTypes,
	}.Build()
	File_pal_address_addresslist_proto = out.File
	file_pal_address_addresslist_proto_rawDesc = nil
	file_pal_address_addresslist_proto_goTypes = nil
	file_pal_address_addresslist_proto_depIdxs = nil
}
