// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: contacts/users.proto

package contacts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Friends struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Email string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *Friends) Reset() {
	*x = Friends{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contacts_users_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Friends) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Friends) ProtoMessage() {}

func (x *Friends) ProtoReflect() protoreflect.Message {
	mi := &file_contacts_users_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Friends.ProtoReflect.Descriptor instead.
func (*Friends) Descriptor() ([]byte, []int) {
	return file_contacts_users_proto_rawDescGZIP(), []int{0}
}

func (x *Friends) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Friends) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Friends) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Friends) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type Pal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Palx []*Friends `protobuf:"bytes,5,rep,name=palx,proto3" json:"palx,omitempty"`
}

func (x *Pal) Reset() {
	*x = Pal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contacts_users_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pal) ProtoMessage() {}

func (x *Pal) ProtoReflect() protoreflect.Message {
	mi := &file_contacts_users_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pal.ProtoReflect.Descriptor instead.
func (*Pal) Descriptor() ([]byte, []int) {
	return file_contacts_users_proto_rawDescGZIP(), []int{1}
}

func (x *Pal) GetPalx() []*Friends {
	if x != nil {
		return x.Palx
	}
	return nil
}

var File_contacts_users_proto protoreflect.FileDescriptor

var file_contacts_users_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x73,
	0x22, 0x59, 0x0a, 0x07, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x2c, 0x0a, 0x03, 0x50,
	0x61, 0x6c, 0x12, 0x25, 0x0a, 0x04, 0x70, 0x61, 0x6c, 0x78, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x46, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x73, 0x52, 0x04, 0x70, 0x61, 0x6c, 0x78, 0x32, 0x3e, 0x0a, 0x0c, 0x50, 0x65, 0x65,
	0x72, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x0a, 0x41, 0x64, 0x64,
	0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x12, 0x11, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63,
	0x74, 0x73, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x1a, 0x0d, 0x2e, 0x63, 0x6f, 0x6e,
	0x74, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x50, 0x61, 0x6c, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x69, 0x32, 0x32, 0x31, 0x30, 0x2f,
	0x70, 0x65, 0x65, 0x72, 0x73, 0x2d, 0x70, 0x65, 0x65, 0x72, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x74,
	0x61, 0x63, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_contacts_users_proto_rawDescOnce sync.Once
	file_contacts_users_proto_rawDescData = file_contacts_users_proto_rawDesc
)

func file_contacts_users_proto_rawDescGZIP() []byte {
	file_contacts_users_proto_rawDescOnce.Do(func() {
		file_contacts_users_proto_rawDescData = protoimpl.X.CompressGZIP(file_contacts_users_proto_rawDescData)
	})
	return file_contacts_users_proto_rawDescData
}

var file_contacts_users_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_contacts_users_proto_goTypes = []interface{}{
	(*Friends)(nil), // 0: contacts.Friends
	(*Pal)(nil),     // 1: contacts.Pal
}
var file_contacts_users_proto_depIdxs = []int32{
	0, // 0: contacts.Pal.palx:type_name -> contacts.Friends
	0, // 1: contacts.PeersService.AddContact:input_type -> contacts.Friends
	1, // 2: contacts.PeersService.AddContact:output_type -> contacts.Pal
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_contacts_users_proto_init() }
func file_contacts_users_proto_init() {
	if File_contacts_users_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_contacts_users_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Friends); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contacts_users_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_contacts_users_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contacts_users_proto_goTypes,
		DependencyIndexes: file_contacts_users_proto_depIdxs,
		MessageInfos:      file_contacts_users_proto_msgTypes,
	}.Build()
	File_contacts_users_proto = out.File
	file_contacts_users_proto_rawDesc = nil
	file_contacts_users_proto_goTypes = nil
	file_contacts_users_proto_depIdxs = nil
}
